### ISSUE TITLE
Allow dynamic length for short_commit

### ISSUE THREAD

**Issue by walro** [dentarg/dyno_metadata#2]
7 is a great default for the length, but some projects need more (and some do with less), see https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892 for some great background info. Something like:

```ruby
def short_commit(length: 7)
  slug_commit[0, length]
end
```

**Comment by dentarg** [comment]
Good suggestion. I'm thinking the keyword argument isn't necessary, example usage:

```ruby
DynoMetadata.short_commit(12)
```
